### ISSUE TITLE
How to select certain files that are not adjacent from one another

### ISSUE THREAD

**Issue by fauzanrh** [PhilRunninger/nerdtree-visual-selection#8]
I'm wondering for a similar feature like Netrw's `mf` or hold ctrl+mouseclicks in any other file managers. Thanks

**Comment by PhilRunninger** [comment]
No, the selection must be done with Vim's Visual selection feature. Some of the commands (`dd`, `m`, and `c`) require confirmation (`Are you sure? Yes/No/All/Cancel`) before they do their job. I can add the same thing to the other commands.
